services:
  mindpal-fastapi:
    build: ./fastapi
    ports:
      - "8080:8080"
    depends_on:
      - mindpal-postgres
    volumes:
      - ./media:/app/media  # 本地 media 資料夾掛載到容器內部的 /app/media      
    networks:
      - webnet

  mindpal-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Asia/Taipei
    ports:
      - "5432:5432"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro  
    networks:
      - webnet

  mindpal-pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - mindpal-postgres
    ports:
      - "5050:80"
    networks:
      - webnet

  mindpal-redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - webnet

networks:
  webnet:
    external: true
